### PR TITLE
Release Notes - Release 19.11.2

### PR DESCRIPTION
**Pull request by matthewmichihara**

### CODE REVIEW

**Comment by etanshaul** [comment]
awesome! could we please see a screenshot of the welcome screen?

**Comment by etanshaul** [comment]
(you can get the welcome screen to always show up locally by hardcoding `true` as the return val in `WelcomeScreenLauncher#checkUpdateAndStoreVersion`)

**Comment by matthewmichihara** [comment]
yup sounds good. For the internal version right?

**Comment by etanshaul** [comment]
oh oops. my fault. I thought this was the internal version. disregard my comment

**Comment by etanshaul** [comment]
markdown looks good.

screenshot is a bit big though. do you think you could scale it down a bit?

**Comment by matthewmichihara** [comment]
> markdown looks good.
> 
> screenshot is a bit big though. do you think you could scale it down a bit?

done

**Pull request merged**
